package com.jarvis.assistant.runtime.plan

/**
 * Plan — a multi-step proposal returned by the LLM (via MultiToolCall) that
 * the [PlanRunner] surfaces to the user as a single short confirmation,
 * then executes step by step with each step journalled for undo.
 *
 * Plans are constructed transiently in memory; once executed they live on
 * disk only via the [JournalEntry] rows so "undo" can replay in reverse.
 *
 * @property id          Process-unique id; used as the foreign key on
 *                       JournalEntry rows so a single undo command can
 *                       grab every step of one plan.
 * @property steps       Ordered list of steps.  Empty plans are not
 *                       constructed — PlanRunner short-circuits.
 * @property summarySpoken One-line summary spoken to the user before
 *                       execution ("Three things — text, reminder, DND.
 *                       Go?"); generated by [PlanRunner.summarise].
 * @property allReversible Cached at construction so the runner can warn
 *                       up-front about irreversible steps.
 */
data class Plan(
    val id: String,
    val steps: List<PlannedStep>,
    val summarySpoken: String,
    val allReversible: Boolean,
    /** Original user transcript — kept for the journal so undo can describe what was undone. */
    val originatingTranscript: String,
    val createdAtMs: Long = System.currentTimeMillis()
)

/**
 * A single tool invocation inside a [Plan].  The runner resolves [toolName]
 * against the live [com.jarvis.assistant.tools.framework.ToolRegistry] just
 * before execution so a stale plan doesn't bind to a tool that has since
 * been removed.
 */
data class PlannedStep(
    val ordinal: Int,
    val toolName: String,
    val argsJson: String,
    /** Short one-noun-phrase label for the spoken summary ("text", "reminder"). */
    val shortLabel: String,
    val reversible: Boolean
)
